---
- name: check k3s install
  shell: k3s kubectl get node
  register: result
  ignore_errors: True

- name: install k3s single node
  shell: 'curl -sfL https://get.k3s.io | sh -'
  args:
    warn: false
  register: out
  when: result is failed

- debug: msg="{{out.stdout_lines}}"
  when: result is failed

- name: make k3s use docker container
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/k3s.service
    state: present
    regexp: 'server'
    line: '    server --docker \'

- name: daemon-reload
  shell: 'systemctl daemon-reload'

- name: restart k3s
  service:
    name: k3s
    state: restarted


