---
- name: check rancher server install
  shell: docker ps | grep "rancher-server"
  register: result
  ignore_errors: True

- name: install rancher server
  shell: docker run -d --name rancher-server -v /opt/data/dokcer/rancher/:/var/lib/rancher/ --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:stable
  when: result is failed

- name: show rancher server already install message
  shell: echo "rancher server already install"
  when: result is succeeded